services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wardrobe_db
      SPRING_DATASOURCE_USERNAME: wardrobe_user
      SPRING_DATASOURCE_PASSWORD: wardrobe_password

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:8080

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wardrobe_db
      MYSQL_USER: wardrobe_user
      MYSQL_PASSWORD: wardrobe_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
